name: daily-push
on:
  schedule:
    - cron: '30 6 * * *'  
 #push:                    #Push事件触发
 #  branches: [ "main" ]
 #pull_request:            #pull事件触发
 #   branches: [ "main" ]    
 #workflow_dispatch:       #手动触发
  repository_dispatch:
    types: [cron-job]  

jobs:
  run-task:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      TZ: Asia/Shanghai
    steps:
      - name: Check Time
        run: |
          echo "System Time (UTC): $(date)"
          echo "Beijing Time (UTC+8): $(TZ='Asia/Shanghai' date)"
      
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python daily_query.py
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
