name: 天气预报推送

on:
  schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早7点
    - cron: '00 4 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-task:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      TZ: Asia/Shanghai
    steps:
      - name: Check Time
        run: |
          echo "System Time (UTC): $(date)"
          echo "Beijing Time (UTC+8): $(TZ='Asia/Shanghai' date)"
      
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python daily_query.py
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
