name: 带参数触发
on:
  workflow_dispatch:
    inputs:
      env:
        description: '环境'
        required: true
        default: 'dev'
        
jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input env
        run: |
          echo "你输入的环境是: ${{ github.event.inputs.env }}"