name: 带参数触发
on:
  workflow_dispatch:
    inputs:
      env:
        description: '环境'
        required: true
        default: 'dev'
        
jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Check Time
        run: |
          echo "System Time (UTC): $(date -u)"
          echo "Beijing Time (UTC+8): $(TZ='Asia/Shanghai' date)"