name: 发消息给飞书
on:
  schedule:
    - cron: '30 6 * * *'  
  workflow_dispatch:
  
jobs:
- name: 发送飞书通知
  uses: x-actions/feishu@master
  if: always()
  with:
    webhook: ${{ secrets.FEISHU_WEBHOOK }}
    msg_type: text
    content: |
      项目：${{ github.repository }}
      状态：${{ job.status }}
      分支：${{ github.ref }}
      日志：${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}