name: daily-push-test
on:
  schedule:
    - cron: '15 * * * *'
      timezone: "Asia/Shanghai"
  workflow_dispatch:
      
jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Check Time
        run: |
          echo "System Time (UTC): $(date)"
          echo "Beijing Time (UTC+8): $(TZ='Asia/Shanghai' date)"    